- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/_navigation.scss
- app/assets/stylesheets/application.scss
- app/views/layouts/_navigation.erb
- app/views/layouts/application.html.erb
- app/views/pages/info.erb
- test/controllers/pages_controller_test.rb
Merged prototype sidenav with master. Has working secondary nav that slides out from the primary nav. No work has yet been done on responsiveness. So don't expect it to work on mobile.
> Navigation

- app/assets/javascripts/_navigation.js
- app/assets/stylesheets/_footer.scss
- app/assets/stylesheets/_header.scss
- app/assets/stylesheets/_navigation.scss
- app/assets/stylesheets/application.scss
- app/views/layouts/_header.erb
- app/views/layouts/_navigation.erb
- app/views/layouts/application.html.erb
Fixed hamburger on navbar for mobiles, added viewport, changed color of background to white and also changed color of footer/header to purple
> Mobile-navbar and alt. changes

- app/assets/stylesheets/_footer.scss
- app/assets/stylesheets/_navigation.scss
- app/assets/stylesheets/colors.scss
- app/assets/stylesheets/templates.scss
- app/views/layouts/_footer.erb
- app/views/layouts/_navigation.erb
Footer finished. Change accent color a bit on Marias bequest. Changed height of hero by 50px.
> Footer heart styling

- app/controllers/orchestra_management_controller.rb
- app/controllers/user_management_controller.rb
- app/database/areas/orchestra_area.rb
- app/views/orchestra_management/index.html.erb
- app/views/user_management/show.html.erb
- config/routes.rb
Fixed column name for user management and added view for managing orchestras.
> Management fixes

- app/assets/javascripts/application.js
- app/assets/javascripts/register.js
- app/assets/stylesheets/_navigation.scss
- app/controllers/application_controller.rb
- app/controllers/concerns/internationalization_concern.rb
- app/controllers/orchestra_controller.rb
- app/views/layouts/_navigation.erb
- app/views/layouts/application.html.erb
- app/views/orchestra/create.html.erb
- app/views/orchestra/index.html.erb
- app/views/orchestra/register.html.erb
- app/views/orchestra/show.html.erb
- app/views/orchestra/show_signup.html.erb
- config/application.rb
- config/initializers/locale.rb
- config/locales/en.yml
- config/locales/sv.yml
- config/routes.rb
There is now a toggle for the current locale of the website. For now this only applies to the orchestra pages but should be expanded to the majority of the site later.
> Offer translation of orchestra pages

- app/views/orchestra_management/index.html.erb
Fixes issue #45. Must be tested with [sof-dbapp#19](https://github.com/studentorkesterfestivalen/sof-dbapp/pull/19).
> Display owner name and e-mail in orchestra management list

- app/views/orchestra_management/index.html.erb
Changed from `Hantera användare` to `Hantera orkestrar`. Fixes issue #50.
> Corrected orchestra management header

- app/views/orchestra/show.html.erb
- app/views/orchestra/show_signup.html.erb
- app/views/orchestra_management/index.html.erb
- app/views/user_management/index.html.erb
> Removed all occurances of responsive-table css class

- app/assets/stylesheets/_footer.scss
- app/views/layouts/_footer.erb
> Sponsor logos link to their respective webpages

- .env
- app.json
- app/assets/stylesheets/application.scss
- app/helpers/application_helper.rb
- app/views/layouts/_debugheader.html.erb
- app/views/layouts/application.html.erb
- config/initializers/database.rb
Default to staging database when developing locally and include a display of the current database in the web UI. Fixes #82.
> Changes to database default and presentation

- app/controllers/navigation_controller.rb
- app/database/failed_response.rb
- app/views/layouts/_loginmenu.html.erb
- app/views/layouts/_menuitem.html.erb
- app/views/layouts/_navigation.erb
Also restructured rendering of menu and allow the app to run without a connected database. Fixes #60
> Added missing method to FailedResponse class (fixes #60)

- app/assets/javascripts/cortege.js
This causes most other scripts, including orchestra signup code verification.
> Fixed error caused by phoneField not always present

- app/assets/javascripts/register.js
- app/controllers/orchestra_controller.rb
- app/views/orchestra/register.html.erb
- config/locales/en.yml
- config/locales/sv.yml
- db/schema.rb
> added new foodticket and fixed a bug where Dam XXXL shirt could be ordered

- app/helpers/application_helper.rb
- app/helpers/orchestra_helper.rb
- app/views/orchestra/show_signup.html.erb
- config/locales/en.yml
- config/locales/sv.yml
Adds the following fields:
- Är detta ditt tioende raka SOF/STORK?
- Har du varit på 25 eller fler SOF/STORK?
- Hur stort är ditt instrument?
> Added missing fields to orchestra signup summary (fixes #101)

- .gitignore
> Remove submodule from version control (fixes #118)

- app/controllers/user_controller.rb
- app/views/layouts/_loginmenu.html.erb
- test/integration/user_creation_test.rb
> Redirect users back to previous page after login, or root if not present

- app/views/layouts/_navigation.erb
> Changed to new logo

- app/controllers/funkis_management_controller.rb
- app/database/areas/funkis_area.rb
- app/helpers/funkis_management_helper.rb
- app/helpers/user_management_helper.rb
- app/views/funkis_management/index.html.erb
- config/routes.rb
Front-end for the statistics functionality available in the accompanying pull request in the database app.
> Funkis stats

- app/helpers/webstore_helper.rb
Requested by cortege-leaders so they can get compensation from their organisations. Fixed #185
> Shows name of owner on products even if its yourself.

- app/assets/stylesheets/frontpage.scss
- app/assets/stylesheets/templates.scss
- app/views/frontpage/index.html.erb
Added movie to frontpage, also made a new templateclass that has a bigger height for a hero to better fit a movie
> Movie frontpage

- app/controllers/cortege_membership_controller.rb
Pulls the error message given from the db app instead of generating one itself.
> Better flash messages on adding/removing cortege members

- app/assets/javascripts/user_management.js
- app/controllers/item_collect_controller.rb
- app/controllers/user_management_controller.rb
- app/database/areas/collect_area.rb
- app/database/areas/user_area.rb
- app/views/item_collect/index.html.erb
- app/views/user_management/index.html.erb
- config/routes.rb
> User Management Improvements
